services:
  server:
    read_only: true
    build:
      context: .
      dockerfile: docker/debian.Dockerfile
      args:
        - CLEVERTAGGER_SHA
        - WAPITI_SHA
    ports:
      - "5003:5003"
    volumes:
      - ./models:/app/models
    tmpfs:
      - /tmp
