services:
  server:
    read_only: true
    build:
      context: .
      dockerfile: docker/debian.Dockerfile
      args:
        - CLEVERTAGGER_SHA
        - WAPITI_SHA
    env_file:
      - .env
    ports:
      - "5003:8000"
    volumes:
      - ./models:/app/models
    tmpfs:
      - /root
      - /tmp
