# Temporary directory
tempdir = local

# Use unique names for temporary files
uniquetmp = 1

# Delete temporary files after parsing
deltemp = 1

# Tagger command
taggercmd = /app/external/clevertagger/clevertagger

# Gertwol commands
gertwolcmd = /opt/bin/uis-gertwol
gertwolscorecmd = /opt/bin/gertwolscore

# Model for SMOR morphological analysis
smor_model = /app/models/parzu.ca

# Morphology
morphology = smor

# Output format
outputformat = conll

# Input format
inputformat = plain

# Number of parallel processes of the main parsing step
processes = 4

# Use nbest tagging output
nbestmode = 0

# Probability cutoff in nbest mode
nbest_cutoff = 0.05
